apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nd5pefka8-python 
  janus-idp.io/tekton: nd5pefka8-python
  backstage.io/kubernetes-id: nd5pefka8-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nd5pefka8-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml